# Generated by Django 4.0.4 on 2022-05-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flightNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=5)),
                ('departureTime', models.CharField(max_length=5)),
                ('arrivalTime', models.CharField(max_length=11)),
                ('departureDate', models.DateField()),
                ('price', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Flights',
            },
        ),
    ]
