# Generated by Django 4.0.4 on 2022-05-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_flights_newdateformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('bRef', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('ppNumber', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust', to='myapp.customer')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='myapp.flights')),
            ],
        ),
    ]
