# Generated by Django 4.0.4 on 2022-05-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_junction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='totalSeats',
            field=models.IntegerField(default=0),
        ),
    ]
