# Generated by Django 4.0.4 on 2022-06-14 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_flights_totalseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bRef', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bRef',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Junction',
        ),
        migrations.AddField(
            model_name='bookings',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust', to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='myapp.flights'),
        ),
    ]
