# Generated by Django 4.0.4 on 2022-06-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bookings_remove_customer_bref_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookings',
            table='Bookings',
        ),
    ]
